export const GlobalTypes = {
    IS_SUBMITTING_POST: "IS_SUBMITTING_POST",
    COUNT_USER_INVITATIONS: "COUNT_USER_INVITATIONS",
    HAS_SUBMITTED_POST: "HAS_SUBMITTED_POST",
    HAS_UPDATED_USER_SETTINGS: "HAS_UPDATED_USER_SETTINGS",
    SET_USER_CONNECTIONS: "SET_USER_CONNECTIONS",
} as const;
