export const GlobalTypes = {
    IS_SUBMITTING_POST: "IS_SUBMITTING_POST",
    COUNT_USER_INVITATIONS: "COUNT_USER_INVITATIONS",
    HAS_SUBMITTED_POST: "HAS_SUBMITTED_POST",
    HAS_UPDATED_USER_SETTINGS: "HAS_UPDATED_USER_SETTINGS",
    SET_USER_CONNECTIONS: "SET_USER_CONNECTIONS",
    HAS_CREATED_EMOTION: "HAS_CREATED_EMOTION",
    SET_CREATED_EMOTION: "SET_CREATED_EMOTION",
    COUNT_NEW_MESSAGES: "COUNT_NEW_MESSAGES",
    SET_CHATS_COUNT_UNSAW_MESSAGES: "SET_CHATS_COUNT_UNSAW_MESSAGES",
    CHATS_COUNT_UNSAW_MESSAGES: "CHATS_COUNT_UNSAW_MESSAGES",
    ADD_MESSAGE_SENDED_TO_STORE: "ADD_MESSAGE_SENDED_TO_STORE",
    CLEAR_MESSAGES_FROM_STORE: "CLEAR_MESSAGES_FROM_STORE",
} as const;
